#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 141
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 71
#define ALIAS_COUNT 0
#define TOKEN_COUNT 37
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 6

enum ts_symbol_identifiers {
  anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN = 1,
  aux_sym_comment_token1 = 2,
  anon_sym_RBRACK = 3,
  anon_sym_LTBOUCLE_ = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_GT = 7,
  anon_sym_LT_SLASHBOUCLE_ = 8,
  anon_sym_LTB_ = 9,
  anon_sym_LT_SLASHB_ = 10,
  anon_sym_LT_SLASH_SLASHB_ = 11,
  sym_loop_name = 12,
  aux_sym_loop_type_token1 = 13,
  anon_sym_LBRACE = 14,
  anon_sym_RBRACE = 15,
  aux_sym_criteria_value_token1 = 16,
  aux_sym_criteria_value_token2 = 17,
  anon_sym_LTINCLURE = 18,
  aux_sym_include_tag_token1 = 19,
  anon_sym_LTmulti_GT = 20,
  anon_sym_LT_SLASHmulti_GT = 21,
  sym_lang_code = 22,
  sym_lang_code_brace = 23,
  sym_multi_text = 24,
  anon_sym_LT_COLON = 25,
  aux_sym_translation_token1 = 26,
  anon_sym_COLON_GT = 27,
  anon_sym_LPAREN_POUND = 28,
  aux_sym_balise_token1 = 29,
  sym_balise_namespace = 30,
  anon_sym_POUND = 31,
  anon_sym_PIPE = 32,
  sym_filter_name = 33,
  sym_conditional_open = 34,
  sym__content_char = 35,
  sym__spip_ws = 36,
  sym_template = 37,
  sym_comment = 38,
  sym_loop_open = 39,
  sym_loop_close = 40,
  sym_loop_conditional_open = 41,
  sym_loop_conditional_close = 42,
  sym_loop_alternative = 43,
  sym_loop_type = 44,
  sym_criteria = 45,
  sym_criteria_value = 46,
  sym_include_tag = 47,
  sym_include_param_block = 48,
  sym_include_params = 49,
  sym_multi_block = 50,
  sym_translation = 51,
  sym_balise = 52,
  sym_balise_name = 53,
  sym_balise_params = 54,
  sym_balise_shorthand = 55,
  sym_filter = 56,
  sym_filter_params = 57,
  sym_param_content = 58,
  sym_conditional_close = 59,
  sym_content = 60,
  aux_sym_template_repeat1 = 61,
  aux_sym_loop_open_repeat1 = 62,
  aux_sym_criteria_value_repeat1 = 63,
  aux_sym_criteria_value_repeat2 = 64,
  aux_sym_criteria_value_repeat3 = 65,
  aux_sym_include_tag_repeat1 = 66,
  aux_sym_multi_block_repeat1 = 67,
  aux_sym_balise_repeat1 = 68,
  aux_sym_balise_repeat2 = 69,
  aux_sym_content_repeat1 = 70,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN] = "[(#REM)",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LTBOUCLE_] = "<BOUCLE_",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASHBOUCLE_] = "</BOUCLE_",
  [anon_sym_LTB_] = "<B_",
  [anon_sym_LT_SLASHB_] = "</B_",
  [anon_sym_LT_SLASH_SLASHB_] = "<//B_",
  [sym_loop_name] = "loop_name",
  [aux_sym_loop_type_token1] = "loop_type_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym_criteria_value_token1] = "criteria_value_token1",
  [aux_sym_criteria_value_token2] = "criteria_value_token2",
  [anon_sym_LTINCLURE] = "<INCLURE",
  [aux_sym_include_tag_token1] = "include_tag_token1",
  [anon_sym_LTmulti_GT] = "<multi>",
  [anon_sym_LT_SLASHmulti_GT] = "</multi>",
  [sym_lang_code] = "lang_code",
  [sym_lang_code_brace] = "lang_code_brace",
  [sym_multi_text] = "multi_text",
  [anon_sym_LT_COLON] = "<:",
  [aux_sym_translation_token1] = "translation_token1",
  [anon_sym_COLON_GT] = ":>",
  [anon_sym_LPAREN_POUND] = "(#",
  [aux_sym_balise_token1] = "balise_token1",
  [sym_balise_namespace] = "balise_namespace",
  [anon_sym_POUND] = "#",
  [anon_sym_PIPE] = "|",
  [sym_filter_name] = "filter_name",
  [sym_conditional_open] = "conditional_open",
  [sym__content_char] = "_content_char",
  [sym__spip_ws] = "_spip_ws",
  [sym_template] = "template",
  [sym_comment] = "comment",
  [sym_loop_open] = "loop_open",
  [sym_loop_close] = "loop_close",
  [sym_loop_conditional_open] = "loop_conditional_open",
  [sym_loop_conditional_close] = "loop_conditional_close",
  [sym_loop_alternative] = "loop_alternative",
  [sym_loop_type] = "loop_type",
  [sym_criteria] = "criteria",
  [sym_criteria_value] = "criteria_value",
  [sym_include_tag] = "include_tag",
  [sym_include_param_block] = "include_param_block",
  [sym_include_params] = "include_params",
  [sym_multi_block] = "multi_block",
  [sym_translation] = "translation",
  [sym_balise] = "balise",
  [sym_balise_name] = "balise_name",
  [sym_balise_params] = "balise_params",
  [sym_balise_shorthand] = "balise_shorthand",
  [sym_filter] = "filter",
  [sym_filter_params] = "filter_params",
  [sym_param_content] = "param_content",
  [sym_conditional_close] = "conditional_close",
  [sym_content] = "content",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_loop_open_repeat1] = "loop_open_repeat1",
  [aux_sym_criteria_value_repeat1] = "criteria_value_repeat1",
  [aux_sym_criteria_value_repeat2] = "criteria_value_repeat2",
  [aux_sym_criteria_value_repeat3] = "criteria_value_repeat3",
  [aux_sym_include_tag_repeat1] = "include_tag_repeat1",
  [aux_sym_multi_block_repeat1] = "multi_block_repeat1",
  [aux_sym_balise_repeat1] = "balise_repeat1",
  [aux_sym_balise_repeat2] = "balise_repeat2",
  [aux_sym_content_repeat1] = "content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN] = anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LTBOUCLE_] = anon_sym_LTBOUCLE_,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASHBOUCLE_] = anon_sym_LT_SLASHBOUCLE_,
  [anon_sym_LTB_] = anon_sym_LTB_,
  [anon_sym_LT_SLASHB_] = anon_sym_LT_SLASHB_,
  [anon_sym_LT_SLASH_SLASHB_] = anon_sym_LT_SLASH_SLASHB_,
  [sym_loop_name] = sym_loop_name,
  [aux_sym_loop_type_token1] = aux_sym_loop_type_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_criteria_value_token1] = aux_sym_criteria_value_token1,
  [aux_sym_criteria_value_token2] = aux_sym_criteria_value_token2,
  [anon_sym_LTINCLURE] = anon_sym_LTINCLURE,
  [aux_sym_include_tag_token1] = aux_sym_include_tag_token1,
  [anon_sym_LTmulti_GT] = anon_sym_LTmulti_GT,
  [anon_sym_LT_SLASHmulti_GT] = anon_sym_LT_SLASHmulti_GT,
  [sym_lang_code] = sym_lang_code,
  [sym_lang_code_brace] = sym_lang_code_brace,
  [sym_multi_text] = sym_multi_text,
  [anon_sym_LT_COLON] = anon_sym_LT_COLON,
  [aux_sym_translation_token1] = aux_sym_translation_token1,
  [anon_sym_COLON_GT] = anon_sym_COLON_GT,
  [anon_sym_LPAREN_POUND] = anon_sym_LPAREN_POUND,
  [aux_sym_balise_token1] = aux_sym_balise_token1,
  [sym_balise_namespace] = sym_balise_namespace,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_filter_name] = sym_filter_name,
  [sym_conditional_open] = sym_conditional_open,
  [sym__content_char] = sym__content_char,
  [sym__spip_ws] = sym__spip_ws,
  [sym_template] = sym_template,
  [sym_comment] = sym_comment,
  [sym_loop_open] = sym_loop_open,
  [sym_loop_close] = sym_loop_close,
  [sym_loop_conditional_open] = sym_loop_conditional_open,
  [sym_loop_conditional_close] = sym_loop_conditional_close,
  [sym_loop_alternative] = sym_loop_alternative,
  [sym_loop_type] = sym_loop_type,
  [sym_criteria] = sym_criteria,
  [sym_criteria_value] = sym_criteria_value,
  [sym_include_tag] = sym_include_tag,
  [sym_include_param_block] = sym_include_param_block,
  [sym_include_params] = sym_include_params,
  [sym_multi_block] = sym_multi_block,
  [sym_translation] = sym_translation,
  [sym_balise] = sym_balise,
  [sym_balise_name] = sym_balise_name,
  [sym_balise_params] = sym_balise_params,
  [sym_balise_shorthand] = sym_balise_shorthand,
  [sym_filter] = sym_filter,
  [sym_filter_params] = sym_filter_params,
  [sym_param_content] = sym_param_content,
  [sym_conditional_close] = sym_conditional_close,
  [sym_content] = sym_content,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_loop_open_repeat1] = aux_sym_loop_open_repeat1,
  [aux_sym_criteria_value_repeat1] = aux_sym_criteria_value_repeat1,
  [aux_sym_criteria_value_repeat2] = aux_sym_criteria_value_repeat2,
  [aux_sym_criteria_value_repeat3] = aux_sym_criteria_value_repeat3,
  [aux_sym_include_tag_repeat1] = aux_sym_include_tag_repeat1,
  [aux_sym_multi_block_repeat1] = aux_sym_multi_block_repeat1,
  [aux_sym_balise_repeat1] = aux_sym_balise_repeat1,
  [aux_sym_balise_repeat2] = aux_sym_balise_repeat2,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTBOUCLE_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASHBOUCLE_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTB_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASHB_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH_SLASHB_] = {
    .visible = true,
    .named = false,
  },
  [sym_loop_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_loop_type_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_criteria_value_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_criteria_value_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LTINCLURE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_include_tag_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LTmulti_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASHmulti_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_lang_code] = {
    .visible = true,
    .named = true,
  },
  [sym_lang_code_brace] = {
    .visible = true,
    .named = true,
  },
  [sym_multi_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_translation_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_balise_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_balise_namespace] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_filter_name] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional_open] = {
    .visible = true,
    .named = true,
  },
  [sym__content_char] = {
    .visible = false,
    .named = true,
  },
  [sym__spip_ws] = {
    .visible = false,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_loop_open] = {
    .visible = true,
    .named = true,
  },
  [sym_loop_close] = {
    .visible = true,
    .named = true,
  },
  [sym_loop_conditional_open] = {
    .visible = true,
    .named = true,
  },
  [sym_loop_conditional_close] = {
    .visible = true,
    .named = true,
  },
  [sym_loop_alternative] = {
    .visible = true,
    .named = true,
  },
  [sym_loop_type] = {
    .visible = true,
    .named = true,
  },
  [sym_criteria] = {
    .visible = true,
    .named = true,
  },
  [sym_criteria_value] = {
    .visible = true,
    .named = true,
  },
  [sym_include_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_include_param_block] = {
    .visible = true,
    .named = true,
  },
  [sym_include_params] = {
    .visible = true,
    .named = true,
  },
  [sym_multi_block] = {
    .visible = true,
    .named = true,
  },
  [sym_translation] = {
    .visible = true,
    .named = true,
  },
  [sym_balise] = {
    .visible = true,
    .named = true,
  },
  [sym_balise_name] = {
    .visible = true,
    .named = true,
  },
  [sym_balise_params] = {
    .visible = true,
    .named = true,
  },
  [sym_balise_shorthand] = {
    .visible = true,
    .named = true,
  },
  [sym_filter] = {
    .visible = true,
    .named = true,
  },
  [sym_filter_params] = {
    .visible = true,
    .named = true,
  },
  [sym_param_content] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional_close] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_loop_open_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_criteria_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_criteria_value_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_criteria_value_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_include_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multi_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_balise_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_balise_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_namespace = 2,
  field_params = 3,
  field_type = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_namespace] = "namespace",
  [field_params] = "params",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_params, 1},
  [2] =
    {field_name, 2},
    {field_namespace, 1},
  [4] =
    {field_value, 1},
  [5] =
    {field_name, 1},
    {field_type, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 46,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 6,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 34,
  [82] = 35,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 126,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(63);
      ADVANCE_MAP(
        '#', 100,
        '(', 69,
        ')', 70,
        '*', 98,
        '/', 14,
        ':', 15,
        '<', 6,
        '>', 71,
        '[', 104,
        ']', 66,
        '_', 77,
        '{', 81,
        '|', 101,
        '}', 82,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(5);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(96);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(33);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 4:
      if (lookahead == ')') ADVANCE(64);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == ':') ADVANCE(92);
      if (lookahead == 'B') ADVANCE(31);
      if (lookahead == 'I') ADVANCE(30);
      if (lookahead == 'm') ADVANCE(49);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == 'B') ADVANCE(32);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == 'B') ADVANCE(32);
      if (lookahead == 'm') ADVANCE(50);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == ':') ADVANCE(92);
      if (lookahead == 'B') ADVANCE(31);
      if (lookahead == 'I') ADVANCE(30);
      if (lookahead == 'm') ADVANCE(49);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != '{') ADVANCE(91);
      END_STATE();
    case 11:
      if (lookahead == '/') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != '{') ADVANCE(91);
      END_STATE();
    case 12:
      if (lookahead == ':') ADVANCE(99);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '<') ADVANCE(10);
      if (lookahead == '[') ADVANCE(53);
      if (lookahead == '{') ADVANCE(56);
      if (lookahead != 0) ADVANCE(91);
      END_STATE();
    case 14:
      if (lookahead == '>') ADVANCE(86);
      END_STATE();
    case 15:
      if (lookahead == '>') ADVANCE(95);
      END_STATE();
    case 16:
      if (lookahead == '>') ADVANCE(87);
      END_STATE();
    case 17:
      if (lookahead == '>') ADVANCE(88);
      END_STATE();
    case 18:
      if (lookahead == 'B') ADVANCE(39);
      END_STATE();
    case 19:
      if (lookahead == 'C') ADVANCE(26);
      END_STATE();
    case 20:
      if (lookahead == 'C') ADVANCE(27);
      END_STATE();
    case 21:
      if (lookahead == 'C') ADVANCE(28);
      END_STATE();
    case 22:
      if (lookahead == 'E') ADVANCE(29);
      END_STATE();
    case 23:
      if (lookahead == 'E') ADVANCE(85);
      END_STATE();
    case 24:
      if (lookahead == 'E') ADVANCE(40);
      END_STATE();
    case 25:
      if (lookahead == 'E') ADVANCE(41);
      END_STATE();
    case 26:
      if (lookahead == 'L') ADVANCE(36);
      END_STATE();
    case 27:
      if (lookahead == 'L') ADVANCE(24);
      END_STATE();
    case 28:
      if (lookahead == 'L') ADVANCE(25);
      END_STATE();
    case 29:
      if (lookahead == 'M') ADVANCE(4);
      END_STATE();
    case 30:
      if (lookahead == 'N') ADVANCE(19);
      END_STATE();
    case 31:
      if (lookahead == 'O') ADVANCE(35);
      if (lookahead == '_') ADVANCE(73);
      END_STATE();
    case 32:
      if (lookahead == 'O') ADVANCE(37);
      if (lookahead == '_') ADVANCE(74);
      END_STATE();
    case 33:
      if (lookahead == 'R') ADVANCE(22);
      END_STATE();
    case 34:
      if (lookahead == 'R') ADVANCE(23);
      END_STATE();
    case 35:
      if (lookahead == 'U') ADVANCE(20);
      END_STATE();
    case 36:
      if (lookahead == 'U') ADVANCE(34);
      END_STATE();
    case 37:
      if (lookahead == 'U') ADVANCE(21);
      END_STATE();
    case 38:
      if (lookahead == ']') ADVANCE(89);
      END_STATE();
    case 39:
      if (lookahead == '_') ADVANCE(75);
      END_STATE();
    case 40:
      if (lookahead == '_') ADVANCE(67);
      END_STATE();
    case 41:
      if (lookahead == '_') ADVANCE(72);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(16);
      END_STATE();
    case 43:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 44:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 45:
      if (lookahead == 'l') ADVANCE(48);
      END_STATE();
    case 46:
      if (lookahead == 'm') ADVANCE(50);
      if (lookahead != 0) ADVANCE(91);
      END_STATE();
    case 47:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 49:
      if (lookahead == 'u') ADVANCE(44);
      END_STATE();
    case 50:
      if (lookahead == 'u') ADVANCE(45);
      END_STATE();
    case 51:
      if (lookahead == '{') ADVANCE(81);
      if (lookahead == '}') ADVANCE(82);
      if (lookahead != 0) ADVANCE(83);
      END_STATE();
    case 52:
      if (lookahead == '}') ADVANCE(90);
      END_STATE();
    case 53:
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 54:
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 55:
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 56:
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 57:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 58:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 59:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 60:
      if (lookahead == '!' ||
          lookahead == '*' ||
          ('<' <= lookahead && lookahead <= '?') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 61:
      if (lookahead != 0 &&
          lookahead != 'm') ADVANCE(91);
      END_STATE();
    case 62:
      if (eof) ADVANCE(63);
      ADVANCE_MAP(
        '#', 100,
        '(', 1,
        '*', 98,
        '<', 9,
        '[', 103,
        ']', 66,
        '_', 57,
        '{', 81,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(80);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_LTBOUCLE_);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == '#') ADVANCE(96);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_LT_SLASHBOUCLE_);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_LTB_);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_LT_SLASHB_);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_LT_SLASH_SLASHB_);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_loop_name);
      if (lookahead == ':') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(79);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_loop_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(79);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_loop_name);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_loop_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_loop_type_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_criteria_value_token1);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_criteria_value_token2);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_LTINCLURE);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_include_tag_token1);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_LTmulti_GT);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_LT_SLASHmulti_GT);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_lang_code);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_lang_code_brace);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_multi_text);
      if (lookahead == '<') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != '{') ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_LT_COLON);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_translation_token1);
      if (lookahead == ':') ADVANCE(58);
      if (lookahead == '|') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_translation_token1);
      if (lookahead == '|') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_COLON_GT);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_LPAREN_POUND);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_balise_token1);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_balise_token1);
      if (lookahead == '*') ADVANCE(97);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_balise_namespace);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_filter_name);
      if (lookahead == '!' ||
          lookahead == '*' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('<' <= lookahead && lookahead <= '?') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_conditional_open);
      if (lookahead == '(') ADVANCE(2);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_conditional_open);
      if (lookahead == '(') ADVANCE(2);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 62, .external_lex_state = 2},
  [2] = {.lex_state = 62, .external_lex_state = 2},
  [3] = {.lex_state = 62, .external_lex_state = 2},
  [4] = {.lex_state = 62, .external_lex_state = 2},
  [5] = {.lex_state = 62, .external_lex_state = 2},
  [6] = {.lex_state = 62, .external_lex_state = 2},
  [7] = {.lex_state = 62, .external_lex_state = 2},
  [8] = {.lex_state = 62, .external_lex_state = 2},
  [9] = {.lex_state = 62, .external_lex_state = 2},
  [10] = {.lex_state = 62, .external_lex_state = 2},
  [11] = {.lex_state = 62, .external_lex_state = 2},
  [12] = {.lex_state = 62, .external_lex_state = 2},
  [13] = {.lex_state = 62, .external_lex_state = 2},
  [14] = {.lex_state = 62, .external_lex_state = 2},
  [15] = {.lex_state = 62, .external_lex_state = 2},
  [16] = {.lex_state = 62, .external_lex_state = 2},
  [17] = {.lex_state = 62, .external_lex_state = 2},
  [18] = {.lex_state = 62, .external_lex_state = 2},
  [19] = {.lex_state = 62, .external_lex_state = 2},
  [20] = {.lex_state = 62, .external_lex_state = 2},
  [21] = {.lex_state = 62, .external_lex_state = 2},
  [22] = {.lex_state = 62, .external_lex_state = 2},
  [23] = {.lex_state = 62, .external_lex_state = 2},
  [24] = {.lex_state = 62, .external_lex_state = 2},
  [25] = {.lex_state = 62, .external_lex_state = 2},
  [26] = {.lex_state = 62, .external_lex_state = 2},
  [27] = {.lex_state = 62, .external_lex_state = 2},
  [28] = {.lex_state = 62, .external_lex_state = 2},
  [29] = {.lex_state = 62, .external_lex_state = 2},
  [30] = {.lex_state = 62, .external_lex_state = 2},
  [31] = {.lex_state = 62, .external_lex_state = 2},
  [32] = {.lex_state = 62, .external_lex_state = 2},
  [33] = {.lex_state = 62, .external_lex_state = 2},
  [34] = {.lex_state = 62, .external_lex_state = 2},
  [35] = {.lex_state = 62, .external_lex_state = 2},
  [36] = {.lex_state = 0, .external_lex_state = 3},
  [37] = {.lex_state = 0, .external_lex_state = 3},
  [38] = {.lex_state = 0, .external_lex_state = 3},
  [39] = {.lex_state = 0, .external_lex_state = 3},
  [40] = {.lex_state = 0, .external_lex_state = 3},
  [41] = {.lex_state = 0, .external_lex_state = 3},
  [42] = {.lex_state = 0, .external_lex_state = 3},
  [43] = {.lex_state = 0, .external_lex_state = 3},
  [44] = {.lex_state = 0, .external_lex_state = 3},
  [45] = {.lex_state = 0, .external_lex_state = 3},
  [46] = {.lex_state = 51},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0, .external_lex_state = 3},
  [49] = {.lex_state = 0, .external_lex_state = 3},
  [50] = {.lex_state = 51},
  [51] = {.lex_state = 0, .external_lex_state = 3},
  [52] = {.lex_state = 0, .external_lex_state = 3},
  [53] = {.lex_state = 0, .external_lex_state = 3},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0, .external_lex_state = 3},
  [56] = {.lex_state = 0, .external_lex_state = 3},
  [57] = {.lex_state = 0, .external_lex_state = 3},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0, .external_lex_state = 3},
  [60] = {.lex_state = 51},
  [61] = {.lex_state = 0, .external_lex_state = 3},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0, .external_lex_state = 3},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 13},
  [66] = {.lex_state = 13},
  [67] = {.lex_state = 13},
  [68] = {.lex_state = 0, .external_lex_state = 3},
  [69] = {.lex_state = 0, .external_lex_state = 3},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 51},
  [72] = {.lex_state = 51},
  [73] = {.lex_state = 51},
  [74] = {.lex_state = 51},
  [75] = {.lex_state = 51},
  [76] = {.lex_state = 51},
  [77] = {.lex_state = 51},
  [78] = {.lex_state = 51},
  [79] = {.lex_state = 0, .external_lex_state = 3},
  [80] = {.lex_state = 51},
  [81] = {.lex_state = 0, .external_lex_state = 3},
  [82] = {.lex_state = 0, .external_lex_state = 3},
  [83] = {.lex_state = 51},
  [84] = {.lex_state = 51},
  [85] = {.lex_state = 0, .external_lex_state = 3},
  [86] = {.lex_state = 51},
  [87] = {.lex_state = 51},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 51},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 51},
  [92] = {.lex_state = 0, .external_lex_state = 3},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0, .external_lex_state = 3},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0, .external_lex_state = 3},
  [97] = {.lex_state = 51},
  [98] = {.lex_state = 0, .external_lex_state = 3},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0, .external_lex_state = 3},
  [102] = {.lex_state = 0, .external_lex_state = 3},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 51},
  [106] = {.lex_state = 0, .external_lex_state = 3},
  [107] = {.lex_state = 0, .external_lex_state = 3},
  [108] = {.lex_state = 62},
  [109] = {.lex_state = 62},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 62},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 62},
  [116] = {.lex_state = 3},
  [117] = {.lex_state = 3},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 3},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 3},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 65},
  [130] = {.lex_state = 58},
  [131] = {.lex_state = 3},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 3},
  [137] = {.lex_state = 60},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 84},
  [140] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LTBOUCLE_] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASHBOUCLE_] = ACTIONS(1),
    [anon_sym_LTB_] = ACTIONS(1),
    [anon_sym_LT_SLASHB_] = ACTIONS(1),
    [anon_sym_LT_SLASH_SLASHB_] = ACTIONS(1),
    [sym_loop_name] = ACTIONS(1),
    [aux_sym_loop_type_token1] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LTINCLURE] = ACTIONS(1),
    [aux_sym_include_tag_token1] = ACTIONS(1),
    [anon_sym_LTmulti_GT] = ACTIONS(1),
    [anon_sym_LT_SLASHmulti_GT] = ACTIONS(1),
    [sym_lang_code] = ACTIONS(1),
    [anon_sym_LT_COLON] = ACTIONS(1),
    [anon_sym_COLON_GT] = ACTIONS(1),
    [anon_sym_LPAREN_POUND] = ACTIONS(1),
    [aux_sym_balise_token1] = ACTIONS(1),
    [sym_balise_namespace] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_conditional_open] = ACTIONS(1),
    [sym__content_char] = ACTIONS(1),
    [sym__spip_ws] = ACTIONS(1),
  },
  [1] = {
    [sym_template] = STATE(138),
    [sym_comment] = STATE(2),
    [sym_loop_open] = STATE(2),
    [sym_loop_close] = STATE(2),
    [sym_loop_conditional_open] = STATE(2),
    [sym_loop_conditional_close] = STATE(2),
    [sym_loop_alternative] = STATE(2),
    [sym_include_tag] = STATE(2),
    [sym_multi_block] = STATE(2),
    [sym_translation] = STATE(2),
    [sym_balise] = STATE(2),
    [sym_balise_shorthand] = STATE(2),
    [sym_conditional_close] = STATE(2),
    [sym_content] = STATE(2),
    [aux_sym_template_repeat1] = STATE(2),
    [aux_sym_content_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN] = ACTIONS(5),
    [anon_sym_RBRACK] = ACTIONS(7),
    [anon_sym_LTBOUCLE_] = ACTIONS(9),
    [anon_sym_LT_SLASHBOUCLE_] = ACTIONS(11),
    [anon_sym_LTB_] = ACTIONS(13),
    [anon_sym_LT_SLASHB_] = ACTIONS(15),
    [anon_sym_LT_SLASH_SLASHB_] = ACTIONS(17),
    [anon_sym_LTINCLURE] = ACTIONS(19),
    [anon_sym_LTmulti_GT] = ACTIONS(21),
    [anon_sym_LT_COLON] = ACTIONS(23),
    [anon_sym_LPAREN_POUND] = ACTIONS(25),
    [anon_sym_POUND] = ACTIONS(27),
    [sym_conditional_open] = ACTIONS(29),
    [sym__content_char] = ACTIONS(31),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(5), 1,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
    ACTIONS(7), 1,
      anon_sym_RBRACK,
    ACTIONS(9), 1,
      anon_sym_LTBOUCLE_,
    ACTIONS(11), 1,
      anon_sym_LT_SLASHBOUCLE_,
    ACTIONS(13), 1,
      anon_sym_LTB_,
    ACTIONS(15), 1,
      anon_sym_LT_SLASHB_,
    ACTIONS(17), 1,
      anon_sym_LT_SLASH_SLASHB_,
    ACTIONS(19), 1,
      anon_sym_LTINCLURE,
    ACTIONS(21), 1,
      anon_sym_LTmulti_GT,
    ACTIONS(23), 1,
      anon_sym_LT_COLON,
    ACTIONS(25), 1,
      anon_sym_LPAREN_POUND,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(31), 1,
      sym__content_char,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      sym_conditional_open,
    STATE(7), 1,
      aux_sym_content_repeat1,
    STATE(3), 14,
      sym_comment,
      sym_loop_open,
      sym_loop_close,
      sym_loop_conditional_open,
      sym_loop_conditional_close,
      sym_loop_alternative,
      sym_include_tag,
      sym_multi_block,
      sym_translation,
      sym_balise,
      sym_balise_shorthand,
      sym_conditional_close,
      sym_content,
      aux_sym_template_repeat1,
  [65] = 17,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(39), 1,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
    ACTIONS(42), 1,
      anon_sym_RBRACK,
    ACTIONS(45), 1,
      anon_sym_LTBOUCLE_,
    ACTIONS(48), 1,
      anon_sym_LT_SLASHBOUCLE_,
    ACTIONS(51), 1,
      anon_sym_LTB_,
    ACTIONS(54), 1,
      anon_sym_LT_SLASHB_,
    ACTIONS(57), 1,
      anon_sym_LT_SLASH_SLASHB_,
    ACTIONS(60), 1,
      anon_sym_LTINCLURE,
    ACTIONS(63), 1,
      anon_sym_LTmulti_GT,
    ACTIONS(66), 1,
      anon_sym_LT_COLON,
    ACTIONS(69), 1,
      anon_sym_LPAREN_POUND,
    ACTIONS(72), 1,
      anon_sym_POUND,
    ACTIONS(75), 1,
      sym_conditional_open,
    ACTIONS(78), 1,
      sym__content_char,
    STATE(7), 1,
      aux_sym_content_repeat1,
    STATE(3), 14,
      sym_comment,
      sym_loop_open,
      sym_loop_close,
      sym_loop_conditional_open,
      sym_loop_conditional_close,
      sym_loop_alternative,
      sym_include_tag,
      sym_multi_block,
      sym_translation,
      sym_balise,
      sym_balise_shorthand,
      sym_conditional_close,
      sym_content,
      aux_sym_template_repeat1,
  [130] = 5,
    ACTIONS(83), 1,
      anon_sym_LBRACE,
    ACTIONS(85), 1,
      aux_sym_balise_token1,
    ACTIONS(87), 1,
      sym_conditional_open,
    STATE(19), 1,
      sym_balise_params,
    ACTIONS(81), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [159] = 4,
    ACTIONS(83), 1,
      anon_sym_LBRACE,
    ACTIONS(91), 1,
      sym_conditional_open,
    STATE(22), 1,
      sym_balise_params,
    ACTIONS(89), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [185] = 2,
    ACTIONS(95), 1,
      sym_conditional_open,
    ACTIONS(93), 16,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LBRACE,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      aux_sym_balise_token1,
      anon_sym_POUND,
  [207] = 4,
    ACTIONS(99), 1,
      sym_conditional_open,
    ACTIONS(101), 1,
      sym__content_char,
    STATE(8), 1,
      aux_sym_content_repeat1,
    ACTIONS(97), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [232] = 4,
    ACTIONS(105), 1,
      sym_conditional_open,
    ACTIONS(107), 1,
      sym__content_char,
    STATE(8), 1,
      aux_sym_content_repeat1,
    ACTIONS(103), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [257] = 2,
    ACTIONS(112), 1,
      sym_conditional_open,
    ACTIONS(110), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [277] = 2,
    ACTIONS(116), 1,
      sym_conditional_open,
    ACTIONS(114), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [297] = 2,
    ACTIONS(120), 1,
      sym_conditional_open,
    ACTIONS(118), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [317] = 2,
    ACTIONS(124), 1,
      sym_conditional_open,
    ACTIONS(122), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [337] = 2,
    ACTIONS(128), 1,
      sym_conditional_open,
    ACTIONS(126), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [357] = 2,
    ACTIONS(132), 1,
      sym_conditional_open,
    ACTIONS(130), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [377] = 2,
    ACTIONS(136), 1,
      sym_conditional_open,
    ACTIONS(134), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [397] = 2,
    ACTIONS(140), 1,
      sym_conditional_open,
    ACTIONS(138), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [417] = 2,
    ACTIONS(144), 1,
      sym_conditional_open,
    ACTIONS(142), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [437] = 2,
    ACTIONS(148), 1,
      sym_conditional_open,
    ACTIONS(146), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [457] = 2,
    ACTIONS(91), 1,
      sym_conditional_open,
    ACTIONS(89), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [477] = 2,
    ACTIONS(152), 1,
      sym_conditional_open,
    ACTIONS(150), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [497] = 2,
    ACTIONS(156), 1,
      sym_conditional_open,
    ACTIONS(154), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [517] = 2,
    ACTIONS(160), 1,
      sym_conditional_open,
    ACTIONS(158), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [537] = 2,
    ACTIONS(164), 1,
      sym_conditional_open,
    ACTIONS(162), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [557] = 2,
    ACTIONS(168), 1,
      sym_conditional_open,
    ACTIONS(166), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [577] = 2,
    ACTIONS(172), 1,
      sym_conditional_open,
    ACTIONS(170), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [597] = 2,
    ACTIONS(176), 1,
      sym_conditional_open,
    ACTIONS(174), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [617] = 2,
    ACTIONS(180), 1,
      sym_conditional_open,
    ACTIONS(178), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [637] = 2,
    ACTIONS(184), 1,
      sym_conditional_open,
    ACTIONS(182), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [657] = 2,
    ACTIONS(188), 1,
      sym_conditional_open,
    ACTIONS(186), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [677] = 2,
    ACTIONS(192), 1,
      sym_conditional_open,
    ACTIONS(190), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [697] = 2,
    ACTIONS(196), 1,
      sym_conditional_open,
    ACTIONS(194), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [717] = 2,
    ACTIONS(200), 1,
      sym_conditional_open,
    ACTIONS(198), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [737] = 2,
    ACTIONS(204), 1,
      sym_conditional_open,
    ACTIONS(202), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [757] = 2,
    ACTIONS(208), 1,
      sym_conditional_open,
    ACTIONS(206), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [777] = 2,
    ACTIONS(212), 1,
      sym_conditional_open,
    ACTIONS(210), 14,
      sym__content_char,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LPAREN_POUNDREM_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LTBOUCLE_,
      anon_sym_LT_SLASHBOUCLE_,
      anon_sym_LTB_,
      anon_sym_LT_SLASHB_,
      anon_sym_LT_SLASH_SLASHB_,
      anon_sym_LTINCLURE,
      anon_sym_LTmulti_GT,
      anon_sym_LT_COLON,
      anon_sym_LPAREN_POUND,
      anon_sym_POUND,
  [797] = 7,
    ACTIONS(214), 1,
      anon_sym_RPAREN,
    ACTIONS(216), 1,
      anon_sym_LBRACE,
    ACTIONS(218), 1,
      aux_sym_balise_token1,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(222), 1,
      sym__spip_ws,
    STATE(42), 2,
      sym_balise_params,
      aux_sym_balise_repeat1,
    STATE(55), 2,
      sym_filter,
      aux_sym_balise_repeat2,
  [821] = 7,
    ACTIONS(216), 1,
      anon_sym_LBRACE,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(224), 1,
      anon_sym_RPAREN,
    ACTIONS(226), 1,
      aux_sym_balise_token1,
    ACTIONS(228), 1,
      sym__spip_ws,
    STATE(41), 2,
      sym_balise_params,
      aux_sym_balise_repeat1,
    STATE(68), 2,
      sym_filter,
      aux_sym_balise_repeat2,
  [845] = 6,
    ACTIONS(216), 1,
      anon_sym_LBRACE,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(230), 1,
      anon_sym_RPAREN,
    ACTIONS(232), 1,
      sym__spip_ws,
    STATE(43), 2,
      sym_balise_params,
      aux_sym_balise_repeat1,
    STATE(48), 2,
      sym_filter,
      aux_sym_balise_repeat2,
  [866] = 6,
    ACTIONS(216), 1,
      anon_sym_LBRACE,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
    ACTIONS(236), 1,
      sym__spip_ws,
    STATE(44), 2,
      sym_balise_params,
      aux_sym_balise_repeat1,
    STATE(63), 2,
      sym_filter,
      aux_sym_balise_repeat2,
  [887] = 6,
    ACTIONS(216), 1,
      anon_sym_LBRACE,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
    ACTIONS(240), 1,
      sym__spip_ws,
    STATE(39), 2,
      sym_balise_params,
      aux_sym_balise_repeat1,
    STATE(56), 2,
      sym_filter,
      aux_sym_balise_repeat2,
  [908] = 6,
    ACTIONS(216), 1,
      anon_sym_LBRACE,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
    ACTIONS(240), 1,
      sym__spip_ws,
    STATE(44), 2,
      sym_balise_params,
      aux_sym_balise_repeat1,
    STATE(56), 2,
      sym_filter,
      aux_sym_balise_repeat2,
  [929] = 6,
    ACTIONS(216), 1,
      anon_sym_LBRACE,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(230), 1,
      anon_sym_RPAREN,
    ACTIONS(232), 1,
      sym__spip_ws,
    STATE(44), 2,
      sym_balise_params,
      aux_sym_balise_repeat1,
    STATE(48), 2,
      sym_filter,
      aux_sym_balise_repeat2,
  [950] = 6,
    ACTIONS(216), 1,
      anon_sym_LBRACE,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(242), 1,
      anon_sym_RPAREN,
    ACTIONS(244), 1,
      sym__spip_ws,
    STATE(44), 2,
      sym_balise_params,
      aux_sym_balise_repeat1,
    STATE(59), 2,
      sym_filter,
      aux_sym_balise_repeat2,
  [971] = 4,
    ACTIONS(248), 1,
      anon_sym_LBRACE,
    ACTIONS(251), 1,
      sym__spip_ws,
    ACTIONS(246), 2,
      anon_sym_RPAREN,
      anon_sym_PIPE,
    STATE(44), 2,
      sym_balise_params,
      aux_sym_balise_repeat1,
  [986] = 4,
    ACTIONS(254), 1,
      anon_sym_GT,
    ACTIONS(256), 1,
      anon_sym_LBRACE,
    ACTIONS(259), 1,
      sym__spip_ws,
    STATE(45), 2,
      sym_criteria,
      aux_sym_loop_open_repeat1,
  [1000] = 5,
    ACTIONS(262), 1,
      anon_sym_LBRACE,
    ACTIONS(264), 1,
      anon_sym_RBRACE,
    ACTIONS(266), 1,
      aux_sym_criteria_value_token1,
    STATE(72), 1,
      aux_sym_criteria_value_repeat3,
    STATE(140), 1,
      sym_param_content,
  [1016] = 5,
    ACTIONS(216), 1,
      anon_sym_LBRACE,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(242), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      sym_balise_params,
    STATE(98), 1,
      sym_filter,
  [1032] = 4,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(242), 1,
      anon_sym_RPAREN,
    ACTIONS(268), 1,
      sym__spip_ws,
    STATE(51), 2,
      sym_filter,
      aux_sym_balise_repeat2,
  [1046] = 3,
    ACTIONS(272), 1,
      anon_sym_LBRACE,
    STATE(94), 1,
      sym_filter_params,
    ACTIONS(270), 3,
      sym__spip_ws,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [1058] = 5,
    ACTIONS(262), 1,
      anon_sym_LBRACE,
    ACTIONS(266), 1,
      aux_sym_criteria_value_token1,
    ACTIONS(274), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      aux_sym_criteria_value_repeat3,
    STATE(126), 1,
      sym_param_content,
  [1074] = 4,
    ACTIONS(276), 1,
      anon_sym_RPAREN,
    ACTIONS(278), 1,
      anon_sym_PIPE,
    ACTIONS(281), 1,
      sym__spip_ws,
    STATE(51), 2,
      sym_filter,
      aux_sym_balise_repeat2,
  [1088] = 4,
    ACTIONS(284), 1,
      anon_sym_GT,
    ACTIONS(286), 1,
      anon_sym_LBRACE,
    ACTIONS(288), 1,
      sym__spip_ws,
    STATE(61), 2,
      sym_criteria,
      aux_sym_loop_open_repeat1,
  [1102] = 4,
    ACTIONS(290), 1,
      anon_sym_LBRACE,
    ACTIONS(293), 1,
      aux_sym_include_tag_token1,
    ACTIONS(295), 1,
      sym__spip_ws,
    STATE(53), 2,
      sym_include_param_block,
      aux_sym_include_tag_repeat1,
  [1116] = 5,
    ACTIONS(216), 1,
      anon_sym_LBRACE,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      sym_balise_params,
    STATE(98), 1,
      sym_filter,
  [1132] = 4,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(230), 1,
      anon_sym_RPAREN,
    ACTIONS(298), 1,
      sym__spip_ws,
    STATE(51), 2,
      sym_filter,
      aux_sym_balise_repeat2,
  [1146] = 4,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
    ACTIONS(300), 1,
      sym__spip_ws,
    STATE(51), 2,
      sym_filter,
      aux_sym_balise_repeat2,
  [1160] = 4,
    ACTIONS(302), 1,
      anon_sym_LBRACE,
    ACTIONS(304), 1,
      aux_sym_include_tag_token1,
    ACTIONS(306), 1,
      sym__spip_ws,
    STATE(53), 2,
      sym_include_param_block,
      aux_sym_include_tag_repeat1,
  [1174] = 5,
    ACTIONS(216), 1,
      anon_sym_LBRACE,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(308), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      sym_balise_params,
    STATE(98), 1,
      sym_filter,
  [1190] = 4,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(308), 1,
      anon_sym_RPAREN,
    ACTIONS(310), 1,
      sym__spip_ws,
    STATE(51), 2,
      sym_filter,
      aux_sym_balise_repeat2,
  [1204] = 5,
    ACTIONS(262), 1,
      anon_sym_LBRACE,
    ACTIONS(266), 1,
      aux_sym_criteria_value_token1,
    ACTIONS(312), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      aux_sym_criteria_value_repeat3,
    STATE(125), 1,
      sym_param_content,
  [1220] = 4,
    ACTIONS(286), 1,
      anon_sym_LBRACE,
    ACTIONS(314), 1,
      anon_sym_GT,
    ACTIONS(316), 1,
      sym__spip_ws,
    STATE(45), 2,
      sym_criteria,
      aux_sym_loop_open_repeat1,
  [1234] = 5,
    ACTIONS(216), 1,
      anon_sym_LBRACE,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(318), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      sym_balise_params,
    STATE(98), 1,
      sym_filter,
  [1250] = 4,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(318), 1,
      anon_sym_RPAREN,
    ACTIONS(320), 1,
      sym__spip_ws,
    STATE(51), 2,
      sym_filter,
      aux_sym_balise_repeat2,
  [1264] = 5,
    ACTIONS(216), 1,
      anon_sym_LBRACE,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      sym_balise_params,
    STATE(98), 1,
      sym_filter,
  [1280] = 3,
    ACTIONS(322), 1,
      anon_sym_LT_SLASHmulti_GT,
    STATE(66), 1,
      aux_sym_multi_block_repeat1,
    ACTIONS(324), 3,
      sym_lang_code,
      sym_lang_code_brace,
      sym_multi_text,
  [1292] = 3,
    ACTIONS(326), 1,
      anon_sym_LT_SLASHmulti_GT,
    STATE(66), 1,
      aux_sym_multi_block_repeat1,
    ACTIONS(328), 3,
      sym_lang_code,
      sym_lang_code_brace,
      sym_multi_text,
  [1304] = 3,
    ACTIONS(331), 1,
      anon_sym_LT_SLASHmulti_GT,
    STATE(65), 1,
      aux_sym_multi_block_repeat1,
    ACTIONS(333), 3,
      sym_lang_code,
      sym_lang_code_brace,
      sym_multi_text,
  [1316] = 4,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
    ACTIONS(335), 1,
      sym__spip_ws,
    STATE(51), 2,
      sym_filter,
      aux_sym_balise_repeat2,
  [1330] = 1,
    ACTIONS(93), 5,
      sym__spip_ws,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      aux_sym_balise_token1,
      anon_sym_PIPE,
  [1338] = 5,
    ACTIONS(216), 1,
      anon_sym_LBRACE,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(230), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      sym_balise_params,
    STATE(98), 1,
      sym_filter,
  [1354] = 4,
    ACTIONS(337), 1,
      anon_sym_LBRACE,
    ACTIONS(339), 1,
      anon_sym_RBRACE,
    ACTIONS(341), 1,
      aux_sym_criteria_value_token1,
    STATE(74), 1,
      aux_sym_criteria_value_repeat2,
  [1367] = 4,
    ACTIONS(262), 1,
      anon_sym_LBRACE,
    ACTIONS(343), 1,
      anon_sym_RBRACE,
    ACTIONS(345), 1,
      aux_sym_criteria_value_token1,
    STATE(75), 1,
      aux_sym_criteria_value_repeat3,
  [1380] = 4,
    ACTIONS(262), 1,
      anon_sym_LBRACE,
    ACTIONS(345), 1,
      aux_sym_criteria_value_token1,
    ACTIONS(347), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      aux_sym_criteria_value_repeat3,
  [1393] = 4,
    ACTIONS(337), 1,
      anon_sym_LBRACE,
    ACTIONS(349), 1,
      anon_sym_RBRACE,
    ACTIONS(351), 1,
      aux_sym_criteria_value_token1,
    STATE(78), 1,
      aux_sym_criteria_value_repeat2,
  [1406] = 4,
    ACTIONS(353), 1,
      anon_sym_LBRACE,
    ACTIONS(356), 1,
      anon_sym_RBRACE,
    ACTIONS(358), 1,
      aux_sym_criteria_value_token1,
    STATE(75), 1,
      aux_sym_criteria_value_repeat3,
  [1419] = 4,
    ACTIONS(262), 1,
      anon_sym_LBRACE,
    ACTIONS(345), 1,
      aux_sym_criteria_value_token1,
    ACTIONS(361), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      aux_sym_criteria_value_repeat3,
  [1432] = 4,
    ACTIONS(363), 1,
      anon_sym_LBRACE,
    ACTIONS(365), 1,
      anon_sym_RBRACE,
    ACTIONS(367), 1,
      aux_sym_criteria_value_token1,
    STATE(83), 1,
      aux_sym_criteria_value_repeat1,
  [1445] = 4,
    ACTIONS(369), 1,
      anon_sym_LBRACE,
    ACTIONS(372), 1,
      anon_sym_RBRACE,
    ACTIONS(374), 1,
      aux_sym_criteria_value_token1,
    STATE(78), 1,
      aux_sym_criteria_value_repeat2,
  [1458] = 3,
    ACTIONS(302), 1,
      anon_sym_LBRACE,
    ACTIONS(306), 1,
      sym__spip_ws,
    STATE(57), 2,
      sym_include_param_block,
      aux_sym_include_tag_repeat1,
  [1469] = 4,
    ACTIONS(262), 1,
      anon_sym_LBRACE,
    ACTIONS(377), 1,
      aux_sym_criteria_value_token1,
    STATE(76), 1,
      aux_sym_criteria_value_repeat3,
    STATE(128), 1,
      sym_criteria_value,
  [1482] = 1,
    ACTIONS(206), 4,
      sym__spip_ws,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_PIPE,
  [1489] = 1,
    ACTIONS(210), 4,
      sym__spip_ws,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_PIPE,
  [1496] = 4,
    ACTIONS(379), 1,
      anon_sym_LBRACE,
    ACTIONS(382), 1,
      anon_sym_RBRACE,
    ACTIONS(384), 1,
      aux_sym_criteria_value_token1,
    STATE(83), 1,
      aux_sym_criteria_value_repeat1,
  [1509] = 4,
    ACTIONS(363), 1,
      anon_sym_LBRACE,
    ACTIONS(387), 1,
      anon_sym_RBRACE,
    ACTIONS(389), 1,
      aux_sym_criteria_value_token1,
    STATE(77), 1,
      aux_sym_criteria_value_repeat1,
  [1522] = 1,
    ACTIONS(246), 4,
      sym__spip_ws,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_PIPE,
  [1529] = 4,
    ACTIONS(262), 1,
      anon_sym_LBRACE,
    ACTIONS(391), 1,
      aux_sym_criteria_value_token1,
    STATE(73), 1,
      aux_sym_criteria_value_repeat3,
    STATE(133), 1,
      sym_include_params,
  [1542] = 1,
    ACTIONS(393), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_criteria_value_token1,
  [1548] = 3,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(242), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      sym_filter,
  [1558] = 1,
    ACTIONS(395), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_criteria_value_token1,
  [1564] = 3,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      sym_filter,
  [1574] = 1,
    ACTIONS(356), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_criteria_value_token1,
  [1580] = 1,
    ACTIONS(397), 3,
      sym__spip_ws,
      anon_sym_LBRACE,
      aux_sym_include_tag_token1,
  [1586] = 3,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(308), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      sym_filter,
  [1596] = 1,
    ACTIONS(399), 3,
      sym__spip_ws,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [1602] = 3,
    ACTIONS(286), 1,
      anon_sym_LBRACE,
    ACTIONS(314), 1,
      anon_sym_GT,
    STATE(102), 1,
      sym_criteria,
  [1612] = 1,
    ACTIONS(293), 3,
      sym__spip_ws,
      anon_sym_LBRACE,
      aux_sym_include_tag_token1,
  [1618] = 1,
    ACTIONS(401), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_criteria_value_token1,
  [1624] = 1,
    ACTIONS(276), 3,
      sym__spip_ws,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [1630] = 3,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(318), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      sym_filter,
  [1640] = 3,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(403), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      sym_filter,
  [1650] = 1,
    ACTIONS(405), 3,
      sym__spip_ws,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [1656] = 1,
    ACTIONS(254), 3,
      sym__spip_ws,
      anon_sym_GT,
      anon_sym_LBRACE,
  [1662] = 3,
    ACTIONS(286), 1,
      anon_sym_LBRACE,
    ACTIONS(407), 1,
      anon_sym_GT,
    STATE(102), 1,
      sym_criteria,
  [1672] = 3,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(409), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      sym_filter,
  [1682] = 1,
    ACTIONS(372), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_criteria_value_token1,
  [1688] = 1,
    ACTIONS(411), 3,
      sym__spip_ws,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [1694] = 1,
    ACTIONS(413), 3,
      sym__spip_ws,
      anon_sym_GT,
      anon_sym_LBRACE,
  [1700] = 3,
    ACTIONS(415), 1,
      aux_sym_loop_type_token1,
    ACTIONS(417), 1,
      sym_balise_namespace,
    STATE(36), 1,
      sym_balise_name,
  [1710] = 2,
    ACTIONS(415), 1,
      aux_sym_loop_type_token1,
    STATE(37), 1,
      sym_balise_name,
  [1717] = 2,
    ACTIONS(302), 1,
      anon_sym_LBRACE,
    STATE(96), 1,
      sym_include_param_block,
  [1724] = 2,
    ACTIONS(216), 1,
      anon_sym_LBRACE,
    STATE(85), 1,
      sym_balise_params,
  [1731] = 2,
    ACTIONS(419), 1,
      aux_sym_loop_type_token1,
    STATE(123), 1,
      sym_loop_type,
  [1738] = 2,
    ACTIONS(286), 1,
      anon_sym_LBRACE,
    STATE(102), 1,
      sym_criteria,
  [1745] = 2,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    STATE(98), 1,
      sym_filter,
  [1752] = 2,
    ACTIONS(421), 1,
      aux_sym_loop_type_token1,
    STATE(4), 1,
      sym_balise_name,
  [1759] = 1,
    ACTIONS(423), 1,
      sym_loop_name,
  [1763] = 1,
    ACTIONS(425), 1,
      anon_sym_LPAREN,
  [1767] = 1,
    ACTIONS(427), 1,
      anon_sym_GT,
  [1771] = 1,
    ACTIONS(429), 1,
      sym_loop_name,
  [1775] = 1,
    ACTIONS(431), 1,
      anon_sym_RPAREN,
  [1779] = 1,
    ACTIONS(433), 1,
      anon_sym_GT,
  [1783] = 1,
    ACTIONS(435), 1,
      sym_loop_name,
  [1787] = 1,
    ACTIONS(437), 1,
      anon_sym_RPAREN,
  [1791] = 1,
    ACTIONS(439), 1,
      anon_sym_GT,
  [1795] = 1,
    ACTIONS(441), 1,
      anon_sym_RBRACE,
  [1799] = 1,
    ACTIONS(443), 1,
      anon_sym_RBRACE,
  [1803] = 1,
    ACTIONS(445), 1,
      anon_sym_RBRACK,
  [1807] = 1,
    ACTIONS(447), 1,
      anon_sym_RBRACE,
  [1811] = 1,
    ACTIONS(449), 1,
      aux_sym_comment_token1,
  [1815] = 1,
    ACTIONS(451), 1,
      aux_sym_translation_token1,
  [1819] = 1,
    ACTIONS(453), 1,
      sym_loop_name,
  [1823] = 1,
    ACTIONS(455), 1,
      anon_sym_GT,
  [1827] = 1,
    ACTIONS(457), 1,
      anon_sym_RBRACE,
  [1831] = 1,
    ACTIONS(459), 1,
      anon_sym_COLON_GT,
  [1835] = 1,
    ACTIONS(461), 1,
      anon_sym_RBRACE,
  [1839] = 1,
    ACTIONS(463), 1,
      sym_loop_name,
  [1843] = 1,
    ACTIONS(465), 1,
      sym_filter_name,
  [1847] = 1,
    ACTIONS(467), 1,
      ts_builtin_sym_end,
  [1851] = 1,
    ACTIONS(469), 1,
      aux_sym_criteria_value_token2,
  [1855] = 1,
    ACTIONS(471), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 65,
  [SMALL_STATE(4)] = 130,
  [SMALL_STATE(5)] = 159,
  [SMALL_STATE(6)] = 185,
  [SMALL_STATE(7)] = 207,
  [SMALL_STATE(8)] = 232,
  [SMALL_STATE(9)] = 257,
  [SMALL_STATE(10)] = 277,
  [SMALL_STATE(11)] = 297,
  [SMALL_STATE(12)] = 317,
  [SMALL_STATE(13)] = 337,
  [SMALL_STATE(14)] = 357,
  [SMALL_STATE(15)] = 377,
  [SMALL_STATE(16)] = 397,
  [SMALL_STATE(17)] = 417,
  [SMALL_STATE(18)] = 437,
  [SMALL_STATE(19)] = 457,
  [SMALL_STATE(20)] = 477,
  [SMALL_STATE(21)] = 497,
  [SMALL_STATE(22)] = 517,
  [SMALL_STATE(23)] = 537,
  [SMALL_STATE(24)] = 557,
  [SMALL_STATE(25)] = 577,
  [SMALL_STATE(26)] = 597,
  [SMALL_STATE(27)] = 617,
  [SMALL_STATE(28)] = 637,
  [SMALL_STATE(29)] = 657,
  [SMALL_STATE(30)] = 677,
  [SMALL_STATE(31)] = 697,
  [SMALL_STATE(32)] = 717,
  [SMALL_STATE(33)] = 737,
  [SMALL_STATE(34)] = 757,
  [SMALL_STATE(35)] = 777,
  [SMALL_STATE(36)] = 797,
  [SMALL_STATE(37)] = 821,
  [SMALL_STATE(38)] = 845,
  [SMALL_STATE(39)] = 866,
  [SMALL_STATE(40)] = 887,
  [SMALL_STATE(41)] = 908,
  [SMALL_STATE(42)] = 929,
  [SMALL_STATE(43)] = 950,
  [SMALL_STATE(44)] = 971,
  [SMALL_STATE(45)] = 986,
  [SMALL_STATE(46)] = 1000,
  [SMALL_STATE(47)] = 1016,
  [SMALL_STATE(48)] = 1032,
  [SMALL_STATE(49)] = 1046,
  [SMALL_STATE(50)] = 1058,
  [SMALL_STATE(51)] = 1074,
  [SMALL_STATE(52)] = 1088,
  [SMALL_STATE(53)] = 1102,
  [SMALL_STATE(54)] = 1116,
  [SMALL_STATE(55)] = 1132,
  [SMALL_STATE(56)] = 1146,
  [SMALL_STATE(57)] = 1160,
  [SMALL_STATE(58)] = 1174,
  [SMALL_STATE(59)] = 1190,
  [SMALL_STATE(60)] = 1204,
  [SMALL_STATE(61)] = 1220,
  [SMALL_STATE(62)] = 1234,
  [SMALL_STATE(63)] = 1250,
  [SMALL_STATE(64)] = 1264,
  [SMALL_STATE(65)] = 1280,
  [SMALL_STATE(66)] = 1292,
  [SMALL_STATE(67)] = 1304,
  [SMALL_STATE(68)] = 1316,
  [SMALL_STATE(69)] = 1330,
  [SMALL_STATE(70)] = 1338,
  [SMALL_STATE(71)] = 1354,
  [SMALL_STATE(72)] = 1367,
  [SMALL_STATE(73)] = 1380,
  [SMALL_STATE(74)] = 1393,
  [SMALL_STATE(75)] = 1406,
  [SMALL_STATE(76)] = 1419,
  [SMALL_STATE(77)] = 1432,
  [SMALL_STATE(78)] = 1445,
  [SMALL_STATE(79)] = 1458,
  [SMALL_STATE(80)] = 1469,
  [SMALL_STATE(81)] = 1482,
  [SMALL_STATE(82)] = 1489,
  [SMALL_STATE(83)] = 1496,
  [SMALL_STATE(84)] = 1509,
  [SMALL_STATE(85)] = 1522,
  [SMALL_STATE(86)] = 1529,
  [SMALL_STATE(87)] = 1542,
  [SMALL_STATE(88)] = 1548,
  [SMALL_STATE(89)] = 1558,
  [SMALL_STATE(90)] = 1564,
  [SMALL_STATE(91)] = 1574,
  [SMALL_STATE(92)] = 1580,
  [SMALL_STATE(93)] = 1586,
  [SMALL_STATE(94)] = 1596,
  [SMALL_STATE(95)] = 1602,
  [SMALL_STATE(96)] = 1612,
  [SMALL_STATE(97)] = 1618,
  [SMALL_STATE(98)] = 1624,
  [SMALL_STATE(99)] = 1630,
  [SMALL_STATE(100)] = 1640,
  [SMALL_STATE(101)] = 1650,
  [SMALL_STATE(102)] = 1656,
  [SMALL_STATE(103)] = 1662,
  [SMALL_STATE(104)] = 1672,
  [SMALL_STATE(105)] = 1682,
  [SMALL_STATE(106)] = 1688,
  [SMALL_STATE(107)] = 1694,
  [SMALL_STATE(108)] = 1700,
  [SMALL_STATE(109)] = 1710,
  [SMALL_STATE(110)] = 1717,
  [SMALL_STATE(111)] = 1724,
  [SMALL_STATE(112)] = 1731,
  [SMALL_STATE(113)] = 1738,
  [SMALL_STATE(114)] = 1745,
  [SMALL_STATE(115)] = 1752,
  [SMALL_STATE(116)] = 1759,
  [SMALL_STATE(117)] = 1763,
  [SMALL_STATE(118)] = 1767,
  [SMALL_STATE(119)] = 1771,
  [SMALL_STATE(120)] = 1775,
  [SMALL_STATE(121)] = 1779,
  [SMALL_STATE(122)] = 1783,
  [SMALL_STATE(123)] = 1787,
  [SMALL_STATE(124)] = 1791,
  [SMALL_STATE(125)] = 1795,
  [SMALL_STATE(126)] = 1799,
  [SMALL_STATE(127)] = 1803,
  [SMALL_STATE(128)] = 1807,
  [SMALL_STATE(129)] = 1811,
  [SMALL_STATE(130)] = 1815,
  [SMALL_STATE(131)] = 1819,
  [SMALL_STATE(132)] = 1823,
  [SMALL_STATE(133)] = 1827,
  [SMALL_STATE(134)] = 1831,
  [SMALL_STATE(135)] = 1835,
  [SMALL_STATE(136)] = 1839,
  [SMALL_STATE(137)] = 1843,
  [SMALL_STATE(138)] = 1847,
  [SMALL_STATE(139)] = 1851,
  [SMALL_STATE(140)] = 1855,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(129),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(131),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(116),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(136),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(119),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(122),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(130),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(115),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_balise_shorthand, 2, 0, 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_balise_shorthand, 2, 0, 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_balise_shorthand, 3, 0, 1),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_balise_shorthand, 3, 0, 1),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_balise_name, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_balise_name, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_balise, 4, 0, 3),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_balise, 4, 0, 3),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop_close, 3, 0, 1),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_loop_close, 3, 0, 1),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop_conditional_open, 3, 0, 1),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_loop_conditional_open, 3, 0, 1),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop_conditional_close, 3, 0, 1),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_loop_conditional_close, 3, 0, 1),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop_alternative, 3, 0, 1),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_loop_alternative, 3, 0, 1),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_tag, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include_tag, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multi_block, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multi_block, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_translation, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_translation, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_balise, 3, 0, 1),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_balise, 3, 0, 1),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multi_block, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multi_block, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_balise, 4, 0, 1),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_balise, 4, 0, 1),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_balise_shorthand, 4, 0, 1),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_balise_shorthand, 4, 0, 1),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_balise, 5, 0, 3),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_balise, 5, 0, 3),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_balise, 5, 0, 1),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_balise, 5, 0, 1),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop_open, 6, 0, 5),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_loop_open, 6, 0, 5),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_balise, 6, 0, 3),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_balise, 6, 0, 3),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_balise, 6, 0, 1),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_balise, 6, 0, 1),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop_open, 7, 0, 5),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_loop_open, 7, 0, 5),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional_close, 1, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional_close, 1, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_balise, 7, 0, 3),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_balise, 7, 0, 3),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_balise, 7, 0, 1),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_balise, 7, 0, 1),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop_open, 8, 0, 5),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_loop_open, 8, 0, 5),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_balise, 8, 0, 3),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_balise, 8, 0, 3),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_balise_params, 2, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_balise_params, 2, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_balise_params, 3, 0, 4),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_balise_params, 3, 0, 4),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_balise_repeat1, 2, 0, 0),
  [248] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_balise_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [251] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_balise_repeat1, 2, 0, 0), SHIFT_REPEAT(111),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_loop_open_repeat1, 2, 0, 0),
  [256] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_loop_open_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [259] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_loop_open_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter, 2, 0, 1),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_balise_repeat2, 2, 0, 0),
  [278] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_balise_repeat2, 2, 0, 0), SHIFT_REPEAT(137),
  [281] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_balise_repeat2, 2, 0, 0), SHIFT_REPEAT(114),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [290] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_include_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_include_tag_repeat1, 2, 0, 0),
  [295] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_include_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(110),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multi_block_repeat1, 2, 0, 0),
  [328] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_multi_block_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_content, 1, 0, 0),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [347] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_params, 1, 0, 0),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [353] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_criteria_value_repeat3, 2, 0, 0), SHIFT_REPEAT(71),
  [356] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_criteria_value_repeat3, 2, 0, 0),
  [358] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_criteria_value_repeat3, 2, 0, 0), SHIFT_REPEAT(75),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_criteria_value, 1, 0, 0),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [369] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_criteria_value_repeat2, 2, 0, 0), SHIFT_REPEAT(84),
  [372] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_criteria_value_repeat2, 2, 0, 0),
  [374] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_criteria_value_repeat2, 2, 0, 0), SHIFT_REPEAT(78),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [379] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_criteria_value_repeat1, 2, 0, 0), SHIFT_REPEAT(139),
  [382] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_criteria_value_repeat1, 2, 0, 0),
  [384] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_criteria_value_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [393] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_criteria_value_repeat1, 3, 0, 0),
  [395] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_criteria_value_repeat3, 3, 0, 0),
  [397] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_param_block, 3, 0, 2),
  [399] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter, 3, 0, 1),
  [401] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_criteria_value_repeat2, 3, 0, 0),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [405] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter_params, 2, 0, 0),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [411] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter_params, 3, 0, 4),
  [413] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_criteria, 3, 0, 4),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [419] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [421] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [423] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [425] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [427] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [429] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [431] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop_type, 1, 0, 0),
  [433] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [435] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [437] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [439] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [441] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [443] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [445] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [447] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [449] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [451] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [453] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [455] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [457] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [459] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [461] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [463] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [465] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [467] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [469] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [471] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__content_char = 0,
  ts_external_token__spip_ws = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__content_char] = sym__content_char,
  [ts_external_token__spip_ws] = sym__spip_ws,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__content_char] = true,
    [ts_external_token__spip_ws] = true,
  },
  [2] = {
    [ts_external_token__content_char] = true,
  },
  [3] = {
    [ts_external_token__spip_ws] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_spip_external_scanner_create(void);
void tree_sitter_spip_external_scanner_destroy(void *);
bool tree_sitter_spip_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_spip_external_scanner_serialize(void *, char *);
void tree_sitter_spip_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_spip(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_spip_external_scanner_create,
      tree_sitter_spip_external_scanner_destroy,
      tree_sitter_spip_external_scanner_scan,
      tree_sitter_spip_external_scanner_serialize,
      tree_sitter_spip_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
